CREATE TABLE IF NOT EXISTS filters (
    FNAME VARCHAR(30) UNIQUE NOT NULL,
    FTYPE VARCHAR(20) NOT NULL,
    FCONFIGURATION JSON NOT NULL,
    FREVERSED BOOL NOT NULL,
    FUSER_ID VARCHAR(20) NOT NULL
)